name: Build and Deploy Documentation

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    # Add steps for other dependencies your project might have

    - name: Build Documentation
      run: |
        yarn api-docs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUBTOKEN }}
        publish_dir: ./api-docs/dist # Set this to the directory where your build output is located
        publish_branch: gh-pages # Target branch to deploy to
